package com.claimflow.domain;

public enum ClaimStatus {
    SUBMITTED, POLICY_VALIDATED, DOCUMENTS_PENDING, DOCUMENTS_VERIFIED,
    FRAUD_SCREENED, ASSESSED, APPROVED, MANUAL_REVIEW, REJECTED, SETTLED, REOPENED
}
