import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, BadgeIndianRupee, CheckCircle2, ChevronRight, ClipboardList, FilePlus2, LayoutDashboard, LogOut, Search, ShieldCheck, Stethoscope, Car, HeartPulse, X } from 'lucide-react';
import { api } from './api';
import './styles.css';

const money = (n) => n == null ? '—' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(n);
const typeIcon = { MOTOR: Car, HEALTH: Stethoscope, LIFE: HeartPulse };
const statusTone = (s) => s === 'SETTLED' ? 'green' : s === 'REJECTED' ? 'red' : s === 'MANUAL_REVIEW' || s === 'DOCUMENTS_PENDING' ? 'amber' : 'blue';

function Login({ onLogin }) {
  return <main className="login-shell"><section className="brand-panel"><div className="brand"><ShieldCheck/> ClaimFlow</div><div><p className="eyebrow">Claims, without the friction</p><h1>A clearer path from incident to settlement.</h1><p>Submit, assess and resolve insurance claims through one transparent workflow.</p></div><div className="trust-row"><span>Secure intake</span><span>Rule-based assessment</span><span>Auditable decisions</span></div></section><section className="login-card"><p className="eyebrow">Welcome back</p><h2>Choose your workspace</h2><p className="muted">This demo uses synthetic accounts.</p><button className="primary wide" onClick={() => onLogin('customer')}>Continue as customer <ChevronRight size={18}/></button><button className="secondary wide" onClick={() => onLogin('admin')}>Open admin console <ChevronRight size={18}/></button><div className="demo-note">Customer: customer / customer123<br/>Admin: admin / admin123</div></section></main>;
}

function Header({ role, onLogout }) { return <header><div className="brand"><ShieldCheck/> ClaimFlow</div><div className="header-right"><span className="role-pill">{role}</span><button className="icon-button" title="Log out" onClick={onLogout}><LogOut size={19}/></button></div></header>; }
function Empty({ onNew }) { return <div className="empty"><div className="empty-icon"><ClipboardList/></div><h3>No claims yet</h3><p>When life happens, start here. Your claim progress will stay visible at every step.</p><button className="primary" onClick={onNew}><FilePlus2 size={18}/> File your first claim</button></div>; }

function ClaimCard({ claim, onOpen }) { const Icon = typeIcon[claim.type] || Activity; return <button className="claim-card" onClick={() => onOpen(claim)}><div className="claim-icon"><Icon/></div><div className="claim-main"><div className="claim-top"><strong>{claim.claimNumber}</strong><span className={`status ${statusTone(claim.status)}`}>{claim.status.replaceAll('_',' ')}</span></div><div className="muted small">{claim.type} · Incident {claim.incidentDate}</div><div className="claim-values"><span><small>Claimed</small>{money(claim.claimedAmount)}</span><span><small>Assessed</small>{money(claim.assessedAmount)}</span></div></div><ChevronRight className="chevron"/></button>; }

const docs = { MOTOR: ['POLICE_REPORT','DAMAGE_PHOTOS','DRIVING_LICENSE'], HEALTH: ['MEDICAL_BILLS','DISCHARGE_SUMMARY','PRESCRIPTION'], LIFE: ['DEATH_CERTIFICATE','IDENTITY_PROOF','NOMINEE_PROOF'] };
const policy = { MOTOR: 'MTR-2026-001', HEALTH: 'HLT-2026-001', LIFE: 'LIF-2026-001' };
function NewClaim({ onClose, onCreated }) {
  const [form,setForm] = useState({ type:'MOTOR', incidentDate:new Date().toISOString().slice(0,10), claimedAmount:'', description:'', documentTypes:[] }); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const toggle = d => setForm(f => ({...f, documentTypes:f.documentTypes.includes(d) ? f.documentTypes.filter(x=>x!==d) : [...f.documentTypes,d]}));
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const result = await api('/api/claims',{method:'POST',body:JSON.stringify({...form,policyNumber:policy[form.type],claimedAmount:Number(form.claimedAmount)})}); onCreated(result); } catch(err){setError(err.message)} finally{setBusy(false)} }
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">First notice of loss</p><h2>Tell us what happened</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><div className="type-grid">{Object.keys(docs).map(t => { const Icon=typeIcon[t]; return <button type="button" className={form.type===t?'type active':'type'} onClick={()=>setForm({...form,type:t,documentTypes:[]})} key={t}><Icon/>{t}</button>})}</div><label>Incident date<input type="date" max={new Date().toISOString().slice(0,10)} value={form.incidentDate} onChange={e=>setForm({...form,incidentDate:e.target.value})} required/></label><label>Claim amount (₹)<input type="number" min="1" step="0.01" value={form.claimedAmount} onChange={e=>setForm({...form,claimedAmount:e.target.value})} placeholder="e.g. 45000" required/></label><label>What happened?<textarea minLength="10" maxLength="1000" rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Share the key details of the incident…" required/></label><fieldset><legend>Documents available <span>(upload stub)</span></legend>{docs[form.type].map(d=><label className="check" key={d}><input type="checkbox" checked={form.documentTypes.includes(d)} onChange={()=>toggle(d)}/><span>{d.replaceAll('_',' ')}</span></label>)}</fieldset>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Submitting…':'Submit claim'} <ChevronRight size={18}/></button></form></div>;
}

function Detail({ claim, role, onClose, onChanged }) { const [reason,setReason]=useState(''); async function reopen(){try{onChanged(await api(`/api/claims/${claim.id}/reopen`,{method:'POST',body:JSON.stringify({reason:reason||'Additional information is available'})},role))}catch(e){alert(e.message)}} async function override(decision){try{onChanged(await api(`/api/admin/claims/${claim.id}/decision`,{method:'PATCH',body:JSON.stringify({decision,reason:reason||'Reviewed by claims administrator'})},'admin'))}catch(e){alert(e.message)}} return <div className="modal-backdrop"><div className="modal detail"><div className="modal-head"><div><p className="eyebrow">{claim.type} claim</p><h2>{claim.claimNumber}</h2></div><button className="icon-button" onClick={onClose}><X/></button></div><span className={`status ${statusTone(claim.status)}`}>{claim.status.replaceAll('_',' ')}</span><div className="detail-amount"><small>Approved payable amount</small><strong>{money(claim.assessedAmount)}</strong><span>Claimed {money(claim.claimedAmount)}</span></div><div className="facts"><div><small>Policy</small><strong>{claim.policyNumber}</strong></div><div><small>Fraud score</small><strong>{claim.fraudScore}/100</strong></div><div><small>Documents</small><strong>{claim.verificationStatus.replaceAll('_',' ')}</strong></div><div><small>Decision</small><strong>{claim.decision?.replaceAll('_',' ') || 'Pending'}</strong></div></div>{claim.decisionReason&&<div className="decision"><ShieldCheck/><div><strong>Decision rationale</strong><p>{claim.decisionReason}</p></div></div>}{claim.settlement&&<div className="settlement"><CheckCircle2/><div><strong>Settlement created</strong><p>{claim.settlement.payoutReference} · {claim.settlement.paymentStatus.replaceAll('_',' ')}</p></div></div>}<h3>Audit timeline</h3><ol className="timeline">{claim.auditTrail.map(e=><li key={e.id}><span/><div><strong>{e.action.replaceAll('_',' ')}</strong><p>{e.detail}</p><small>{new Date(e.occurredAt).toLocaleString()}</small></div></li>)}</ol>{((role==='customer'&&['SETTLED','REJECTED'].includes(claim.status))||role==='admin')&&<div className="actions"><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason or reviewer note"/>{role==='customer'?<button className="secondary" onClick={reopen}>Reopen claim</button>:<><button className="secondary" onClick={()=>override('REJECT')}>Reject</button><button className="primary" onClick={()=>override('AUTO_APPROVE')}>Approve</button></>}</div>}</div></div>; }

function Customer({ onSelect, onNew, refresh }) { const [claims,setClaims]=useState([]); const [loading,setLoading]=useState(true); useEffect(()=>{api('/api/claims').then(setClaims).finally(()=>setLoading(false))},[refresh]); return <main className="page"><div className="page-title"><div><p className="eyebrow">Customer portal</p><h1>Your claims</h1><p>Everything you need, from first notice to final settlement.</p></div><button className="primary" onClick={onNew}><FilePlus2 size={18}/> New claim</button></div><section className="summary"><div><span className="summary-icon blue"><ClipboardList/></span><p>All claims<strong>{claims.length}</strong></p></div><div><span className="summary-icon amber"><Activity/></span><p>In progress<strong>{claims.filter(c=>!['SETTLED','REJECTED'].includes(c.status)).length}</strong></p></div><div><span className="summary-icon green"><BadgeIndianRupee/></span><p>Total settled<strong>{money(claims.filter(c=>c.status==='SETTLED').reduce((a,c)=>a+Number(c.assessedAmount||0),0))}</strong></p></div></section><section className="list"><div className="section-head"><h2>Recent claims</h2><Search/></div>{loading?<div className="loading">Loading claims…</div>:claims.length?claims.map(c=><ClaimCard claim={c} onOpen={onSelect} key={c.id}/>):<Empty onNew={onNew}/>}</section></main>; }

function Admin({ onSelect, refresh }) { const [claims,setClaims]=useState([]),[dash,setDash]=useState(null); useEffect(()=>{Promise.all([api('/api/admin/claims',{},'admin'),api('/api/admin/dashboard',{},'admin')]).then(([c,d])=>{setClaims(c);setDash(d)})},[refresh]); return <main className="page"><div className="page-title"><div><p className="eyebrow">Operations console</p><h1>Claims overview</h1><p>Monitor risk, reviews and settlement progress.</p></div><span className="live"><i/> Live workflow</span></div><section className="summary admin-summary"><div><span className="summary-icon blue"><LayoutDashboard/></span><p>Total claims<strong>{dash?.totalClaims ?? '—'}</strong></p></div><div><span className="summary-icon amber"><Activity/></span><p>Manual review<strong>{dash?.openReviews ?? '—'}</strong></p></div><div><span className="summary-icon green"><CheckCircle2/></span><p>Settled<strong>{dash?.settledClaims ?? '—'}</strong></p></div></section><section className="list"><div className="section-head"><h2>Claim queue</h2><span className="muted small">Select a claim to review or override</span></div>{claims.map(c=><ClaimCard claim={c} onOpen={onSelect} key={c.id}/>)}</section></main>; }

function App(){const [role,setRole]=useState(localStorage.getItem('claimflow-role')); const [modal,setModal]=useState(null); const [selected,setSelected]=useState(null); const [refresh,setRefresh]=useState(0); function login(r){localStorage.setItem('claimflow-role',r);setRole(r)} function logout(){localStorage.removeItem('claimflow-role');setRole(null)} function changed(c){setSelected(c);setRefresh(x=>x+1)} if(!role)return <Login onLogin={login}/>; return <><Header role={role} onLogout={logout}/>{role==='admin'?<Admin refresh={refresh} onSelect={setSelected}/>:<Customer refresh={refresh} onSelect={setSelected} onNew={()=>setModal('new')}/>} {modal==='new'&&<NewClaim onClose={()=>setModal(null)} onCreated={c=>{setModal(null);setSelected(c);setRefresh(x=>x+1)}}/>}{selected&&<Detail claim={selected} role={role} onClose={()=>setSelected(null)} onChanged={changed}/>}</>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
